# Generated by Django 3.2.3 on 2021-06-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='pdf',
        ),
        migrations.AddField(
            model_name='reports',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reports',
            name='calcium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='reports',
            name='cholesterol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='reports',
            name='co2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='reports',
            name='date1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='reports',
            name='gender',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='reports',
            name='glucose',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='reports',
            name='iron',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='reports',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='reports',
            name='phosphate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='reports',
            name='potassium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='reports',
            name='sodium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
