# Generated by Django 3.2.3 on 2021-06-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(default='', max_length=25)),
                ('doj', models.CharField(default='', max_length=10)),
                ('salary', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='lab_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqp_name', models.CharField(default='', max_length=50)),
                ('eqp_status', models.CharField(default='OK', max_length=10)),
                ('eqp_condition', models.IntegerField(default=100)),
            ],
        ),
    ]
