# Generated by Django 3.2.3 on 2021-07-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_patient_phn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='d',
            field=models.IntegerField(default=1),
        ),
    ]
